os:
  - linux
language: node_js
node_js:
  - '12'
  - '11'
  - '10'
dist: xenial
sudo: required
services:
  - xvfb
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
install:
  - npm set progress=false
  - npm install
script:
  - npm run build
  - npm run electron:linux
deploy:
  provider: releases
  api_key: $API_KEY
  file: 'release/SurvShell'
  skip_cleanup: true
  on:
    tags: true
